# Generated by Django 5.0.6 on 2024-06-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbDestructura',
            fields=[
                ('id_estructura', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estructura', models.CharField(max_length=255)),
                ('codigo_externo', models.CharField(max_length=255)),
                ('codigo_area', models.CharField(max_length=255)),
                ('siglas', models.TextField(blank=True, null=True)),
                ('estructura_consejo', models.BooleanField(blank=True, null=True)),
                ('estructura_credencial', models.BooleanField(blank=True, null=True)),
                ('guardia', models.BooleanField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_destructura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDinmueble',
            fields=[
                ('id_inmueble', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_inmueble', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_dinmueble',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDpersona',
            fields=[
                ('id_persona', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('carne_identidad', models.CharField(max_length=255)),
                ('solapin', models.CharField(blank=True, max_length=255, null=True)),
                ('id_expediente', models.CharField(blank=True, max_length=255, null=True)),
                ('residente', models.BooleanField()),
                ('activo', models.BooleanField()),
                ('baja', models.BooleanField()),
                ('a_busqueda', models.CharField(blank=True, max_length=255, null=True)),
                ('usuario', models.TextField(blank=True, null=True)),
                ('segundo_nombre', models.CharField(blank=True, null=True)),
                ('primer_apellido', models.CharField(blank=True, null=True)),
                ('segundo_apellido', models.CharField(blank=True, null=True)),
                ('edificio', models.CharField(blank=True, null=True)),
                ('apartamento', models.CharField(blank=True, null=True)),
                ('primer_nombre', models.CharField(blank=True, null=True)),
                ('id_ano_academico', models.IntegerField(blank=True, null=True)),
                ('id_parentesco', models.IntegerField(blank=True, null=True)),
                ('correo', models.TextField(blank=True, null=True)),
                ('id_persona_familiar', models.CharField(blank=True, db_comment='En este campo se guarda el id_persona de la persona que le reserva al familiar,', max_length=255, null=True)),
                ('id_ano_academico_profesor', models.CharField(blank=True, max_length=255, null=True)),
                ('trans_reservado', models.BooleanField(blank=True, null=True)),
                ('trans_distribuido', models.BooleanField(blank=True, null=True)),
                ('trans_cancelado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dpersona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDpersonaFoto',
            fields=[
                ('foto', models.BinaryField(blank=True, null=True)),
                ('color_foto', models.CharField(blank=True, max_length=50, null=True)),
                ('id_persona_foto', models.AutoField(primary_key=True, serialize=False)),
                ('id_foto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dpersona_foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNanoAcademico',
            fields=[
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_ano_academico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_ano_academico', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion_ano_academico', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_nano_academico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNcaracteristicaPersona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('method_service', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_ncaracteristica_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNcargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ncargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNcategoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('fecha_registro_categoria', models.DateTimeField()),
                ('descripcion_categoria', models.TextField()),
                ('activo_categoria', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_ncategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNmunicipio',
            fields=[
                ('id_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=255)),
                ('fecha_registro_municipio', models.DateTimeField()),
                ('descripcion_municipio', models.TextField()),
                ('codigo_oficial_municipio', models.CharField(max_length=255, unique=True)),
                ('activo_municipio', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_nmunicipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNparentesco',
            fields=[
                ('activo', models.BooleanField(blank=True, null=True)),
                ('id_parentesco', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_parentesco', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('descripcion_parentesco', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_nparentesco',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNprovincia',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=255)),
                ('fecha_registro_provincia', models.DateTimeField()),
                ('descripcion_provincia', models.TextField()),
                ('codigo_oficial_provincia', models.CharField(max_length=255)),
                ('activo_provincia', models.BooleanField()),
                ('abreviatura', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_pais', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'tb_nprovincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNsexo',
            fields=[
                ('id_sexo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_sexo', models.CharField(max_length=255)),
                ('fecha_registro_sexo', models.DateTimeField()),
                ('descripcion_sexo', models.TextField()),
                ('activo_sexo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_nsexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNtipoEstructura',
            fields=[
                ('id_tipo_estructura', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_estructura', models.CharField(max_length=255)),
                ('fecha_registro_tipo_estructura', models.DateTimeField()),
                ('descripcion_tipo_estructura', models.TextField(blank=True, null=True)),
                ('activo_tipo_estructura', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_ntipo_estructura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNtipoInmueble',
            fields=[
                ('id_tipo_inmueble', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_inmueble', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_ntipo_inmueble',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRinmueblePersona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_rinmueble_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRpersonaFamiliar',
            fields=[
                ('id_persona_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_rpersona_familiar',
                'managed': False,
            },
        ),
    ]
