# Generated by Django 5.0.6 on 2024-06-03 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbDasignacion',
            fields=[
                ('id_asignacion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_persona_registro', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dasignacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDasistencia',
            fields=[
                ('id_asistencia', models.IntegerField(primary_key=True, serialize=False)),
                ('asistencia', models.BooleanField()),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_dasistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDasistenciaOg',
            fields=[
                ('id_asistencia_og', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_persona_registro', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dasistencia_og',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDconfiguracion',
            fields=[
                ('id_configuracion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_configuracion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_dconfiguracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDdiasPersona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_persona', models.CharField(max_length=255)),
                ('turnos', models.TextField(blank=True, db_comment='(DC2Type:array)', null=True)),
                ('dias', models.TextField(blank=True, db_comment='(DC2Type:array)', null=True)),
            ],
            options={
                'db_table': 'tb_ddias_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDejecucionDePlanificacion',
            fields=[
                ('id_ejecucion_planificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'tb_dejecucion_de_planificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDequipo',
            fields=[
                ('id_equipo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_dequipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDgrupoGuardia',
            fields=[
                ('id_grupo_guardia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_grupo_guardia', models.CharField(max_length=255)),
                ('cantidad_personas_maxima', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('id_grupo_guardia_estructura', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dgrupo_guardia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDincidencia',
            fields=[
                ('id_incidencia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'tb_dincidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDpatron',
            fields=[
                ('id_patron', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('periodicidad', models.IntegerField()),
                ('rotacion_turnos', models.TextField(db_comment='(DC2Type:array)')),
                ('rotacion_dias', models.TextField(db_comment='(DC2Type:array)')),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_dpatron',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDpersonaGuardia',
            fields=[
                ('id_persona', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dpersona_guardia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDplanificacion',
            fields=[
                ('id_planificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_planificacion', models.CharField(max_length=255, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('id_persona_publicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dplanificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDposta',
            fields=[
                ('id_posta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_posta', models.CharField(max_length=255)),
                ('localizacion', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField()),
                ('cantidad_personas', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_dposta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDrecurso',
            fields=[
                ('id_recurso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_recurso', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_drecurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDregionGuardia',
            fields=[
                ('id_region_guardia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_region_guardia', models.CharField(max_length=255)),
                ('activo', models.BooleanField()),
                ('id_responsable', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('id_planificador', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('id_estructura', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dregion_guardia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDsincronizacion',
            fields=[
                ('id_sincronizacion', models.AutoField(primary_key=True, serialize=False)),
                ('host', models.TextField(blank=True, null=True)),
                ('puerto', models.TextField()),
                ('usuario', models.TextField()),
                ('contrasena', models.TextField()),
                ('nombre_bd', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dsincronizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDsolicitudCambio',
            fields=[
                ('id_solicitud_cambio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('motivo', models.TextField()),
                ('aprobadacambiador', models.BooleanField(blank=True, null=True)),
                ('aprobadaplanificador', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_dsolicitud_cambio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbDvariable',
            fields=[
                ('id_variable', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_variable', models.CharField(max_length=250, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_dvariable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNdiaFestivo',
            fields=[
                ('id_dia_festivo', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('todos_anhos', models.BooleanField()),
                ('nombre_dia_festivo', models.CharField(max_length=250)),
                ('dia_semana_mes', models.CharField(blank=True, max_length=20, null=True)),
                ('metodo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_ndia_festivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNdias',
            fields=[
                ('id_dias', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_ndias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNdiasAMostrar',
            fields=[
                ('id_dias_a_mostrar', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_dias_a_mostrar', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_ndias_a_mostrar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNestadoPlan',
            fields=[
                ('id_estado_plan', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_estado_plan', models.CharField(max_length=250, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('fecharegistro', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_nestado_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNhorario',
            fields=[
                ('id_horario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_horario', models.CharField(max_length=250, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_nhorario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNmetodo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField()),
                ('entity', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('method_service', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_nmetodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNtipoIncidencia',
            fields=[
                ('id_tipo_incidencia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_incidencia', models.CharField(max_length=250, unique=True)),
                ('color', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=1000, null=True)),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'tb_ntipo_incidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNtipoPeriodicidad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'tb_ntipo_periodicidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNtipoPlanificacion',
            fields=[
                ('id_tipo_planificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_planificacion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_ntipo_planificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNtipoRecurso',
            fields=[
                ('id_tipo_recurso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_recurso', models.CharField(max_length=250, unique=True)),
                ('fecha_registro_tipo_recurso', models.DateTimeField()),
                ('descripcion_tipo_recurso', models.TextField(blank=True, null=True)),
                ('activo_tipo_recurso', models.BooleanField()),
            ],
            options={
                'db_table': 'tb_ntipo_recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNturno',
            fields=[
                ('id_turno', models.IntegerField(primary_key=True, serialize=False)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('nombre_turno', models.CharField(max_length=250)),
                ('activo', models.BooleanField()),
                ('nombre_notificacion', models.CharField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_nturno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbNultimasGuardias',
            fields=[
                ('id_ultimas_guardias', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_ultimas_guardias', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_nultimas_guardias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRgrupoGuardiaEstructura',
            fields=[
                ('id_grupo_guardia_estructura', models.AutoField(primary_key=True, serialize=False)),
                ('id_estructura', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_rgrupo_guardia_estructura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRgrupoGuardiaPersona',
            fields=[
                ('id_grupo_guardia_persona', models.AutoField(primary_key=True, serialize=False)),
                ('id_persona', models.TextField()),
                ('id_estructura_credencial', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_rgrupo_guardia_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRpersonaGuardiaDiaFestivo',
            fields=[
                ('id_persona_guardia_dia_festivo', models.AutoField(primary_key=True, serialize=False)),
                ('anho', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_rpersona_guardia_dia_festivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRpersonaGuardiaVariable',
            fields=[
                ('id_persona_guardia', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_rpersona_guardia_variable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRpersonaPatron',
            fields=[
                ('id_rpersona_patron', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_rpersona_patron',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRpersonaVariable',
            fields=[
                ('id_rpersona_variable', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tb_rpersona_variable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRregionHorario',
            fields=[
                ('id_rregion_horario', models.IntegerField(primary_key=True, serialize=False)),
                ('arreglo', models.TextField(blank=True, db_comment='(DC2Type:array)', null=True)),
            ],
            options={
                'db_table': 'tb_rregion_horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRregionHorarioDia2',
            fields=[
                ('id_region_horario_dia', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField(blank=True, db_comment='no esta referianciado por no existir una tabla que registre los dias de la semana, los posibles valores serian: 0-1-2-3-4-5-6-7, siendo 0 == domingo', null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_rregion_horario_dia2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRregionHorarioTurno',
            fields=[
                ('id_region_horario_turno', models.IntegerField(primary_key=True, serialize=False)),
                ('turnos', models.TextField(db_comment='(DC2Type:array)')),
            ],
            options={
                'db_table': 'tb_rregion_horario_turno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRregionHorarioTurno2',
            fields=[
                ('id_region_horario_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_rregion_horario_turno2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRtipoRecursoPosta',
            fields=[
                ('id_rtipo_recurso_posta', models.IntegerField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tb_rtipo_recurso_posta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRvariableConfiguracion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('negacion', models.BooleanField()),
                ('tipo_atributo', models.CharField(max_length=255)),
                ('arreglo', models.TextField(db_comment='(DC2Type:array)')),
            ],
            options={
                'db_table': 'tb_rvariable_configuracion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TbRhorarioTurno',
            fields=[
                ('id_horario', models.OneToOneField(db_column='id_horario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.tbnhorario')),
            ],
            options={
                'db_table': 'tb_rhorario_turno',
                'managed': False,
            },
        ),
    ]
