# Generated by Django 5.0.6 on 2024-06-03 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbdplanificacion',
            table='sq_goe.tb_dplanificacion',
        ),
    ]
